import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube} from "react-icons/ai"
import Image from 'next/image'
import deved from '../public/dev-ed-wave.png'
import design from '../public/design.png'
import code from '../public/code.png'
import consulting from '../public/consulting.png'
import web1 from '../public/web1.png'
import web2 from '../public/web2.png'
import web3 from '../public/web3.png'
import web4 from '../public/web4.png'
import web5 from '../public/web5.png'
import web6 from '../public/web6.png'
import { useState } from 'react'



export default function Home() {
  const [darkMode, setDarkMode] = useState(false)
  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Dikeh Daniel Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=' bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        
        <section className=' min-h-screen'>

          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className=' text-xl font-burtons dark:text-teal-600'>developedbyDaniel</h1>
            <ul className=' flex items-center'>
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className=' text-2xl cursor-pointer dark:text-white'/>
              </li>
              <li><a href="#" className=' bg-gradient-to-b from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8 '>Resume</a></li>
            </ul>
          </nav> 

          <div className=" text-center ">
            <h2 className=' text-5xl py-2 text-teal-600 font-medium md:text-6xl'>Dikeh Daniel</h2>
            <h3 className=' text-2xl py-2 md:text-3xl dark:text-white'>Frontend Developer</h3>
            <p className=' text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-white'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, voluptates? Illo explicabo natus sapiente, placeat neque doloremque laborum, fuga provident tempora assumenda suscipit. Architecto quae ex in voluptatibus, assumenda velit?</p>            
          </div> 

          <div className=" flex text-5xl justify-center gap-16 py-3 text-gray-600 ">
            <AiFillTwitterCircle className=' cursor-pointer'/>
            <AiFillLinkedin className=' cursor-pointer'/>
            <AiFillYoutube className=' cursor-pointer'/>
          </div>

          <div className=" relative bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 mx-auto overflow-hidden md:w-96 md:h-96">
            <Image src={deved} layout="fill" objectFit='cover' />
          </div>
        </section>

        {/*  */}

        <section>
          <div className=" mt-10">
            <h3 className=' text-3xl py-1 dark:text-white'>Services I Offer</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-white'>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolorem culpa error minima deserunt provident consequuntur enim numquam. Enim perspiciatis et, voluptate ipsam veniam excepturi molestiae, repudiandae, dolores saepe dolorem praesentium!
            Lorem ipsum dolor sit amet consectetur <span className=' text-teal-500'>adipisicing</span> elit. Maxime doloribus in aliquam provident et eligendi, minima facere possimus quis corporis quae <span className="text-teal-500">voluptatum</span> dolor voluptatem hic eius quam ducimus. Placeat, quod!</p>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-white'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium temporibus sed blanditiis itaque perferendis doloribus veritatis? Modi quisquam. </p>
          </div>

          <div className=' lg:flex gap-10'>
            <div className=" text-center shadow-lg p-10 rounded-xl my-10 lg:px-5 dark:bg-white">
              <Image src={design} width={100} height={100}/>
              <h3 className=' text-lg font-medium pb-2 pt-8'>Beautiful Designs</h3>
              <p className=' py-2'>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Sit, ipsum id sint eveniet recusanda.</p>
              <h4 className=' py-4 text-teal-600'>Design tools i use:</h4>
              <p className=' text-gray-800 py-1'>Photoshoot</p>
              <p className=' text-gray-800 py-1'>Figma</p>
              <p className=' text-gray-800 py-1'>Invision Studio</p>
            </div>

            <div className=" text-center shadow-lg p-10 rounded-xl my-10 lg:px-5 dark:bg-white">
              <Image src={consulting} width={100} height={100}/>
              <h3 className=' text-lg font-medium pb-2 pt-8'>Beautiful Designs</h3>
              <p className=' py-2'>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Sit, ipsum id sint eveniet recusanda.</p>
              <h4 className=' py-4 text-teal-600'>Design tools i use:</h4>
              <p className=' text-gray-800 py-1'>Photoshoot</p>
              <p className=' text-gray-800 py-1'>Figma</p>
              <p className=' text-gray-800 py-1'>Invision Studio</p>
            </div>

            <div className=" text-center shadow-lg p-10 rounded-xl my-10 lg:px-5 dark:bg-white">
              <Image src={code} width={100} height={100}/>
              <h3 className=' text-lg font-medium pb-2 pt-8'>Beautiful Designs</h3>
              <p className=' py-2'>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Sit, ipsum id sint eveniet recusanda.</p>
              <h4 className=' py-4 text-teal-600'>Design tools i use:</h4>
              <p className=' text-gray-800 py-1'>Photoshoot</p>
              <p className=' text-gray-800 py-1'>Figma</p>
              <p className=' text-gray-800 py-1'>Invision Studio</p>
            </div>
          </div>
        </section>

        <section>
          <div className="">
            <h3 className=' text-3xl py-1 dark:text-white'>Portfolio</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-white'>Lorem ipsum dolor sit, Enim perspiciatis et, voluptate ipsam veniam excepturi molestiae, repudiandae, dolores saepe dolorem praesentium!
            Lorem ipsum dolor sit amet consectetur <span className=' text-teal-500'>adipisicing</span> elit. Maxime et eligendi, minima facere possimus quis corporis quae <span className="text-teal-500">voluptatum</span> dolor voluptatem hic eius quam ducimus. Placeat, quod!</p>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-white'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium temporibus sed blanditiis itaque . </p>
          </div>

          <div className=' flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap '>
            <div className=" basis-1/3 flex-1">
              <Image src={web1} 
              className=" object-cover rou rounded-lg cursor-pointer" 
              width={"100%"} 
              height={'100%'} 
              layout="responsive"/>
            </div>

            <div className=" basis-1/3 flex-1">
              <Image src={web2} 
              className=" object-cover rounded-lg cursor-pointer" 
              width={"100%"} 
              height={'100%'} 
              layout="responsive"/>
            </div>

            <div className=" basis-1/3 flex-1">
              <Image src={web3} 
              className=" object-cover rounded-lg cursor-pointer" 
              width={"100%"} 
              height={'100%'} 
              layout="responsive"/>
            </div>

            <div className=" basis-1/3 flex-1">
              <Image src={web4} 
              className=" object-cover rounded-lg cursor-pointer" 
              width={"100%"} 
              height={'100%'} 
              layout="responsive"/>
            </div>

            <div className=" basis-1/3 flex-1">
              <Image src={web5} 
              className=" object-cover rounded-lg cursor-pointer" 
              width={"100%"} 
              height={'100%'} 
              layout="responsive"/>
            </div>

            <div className=" basis-1/3 flex-1">
              <Image src={web6} 
              className=" object-cover rounded-lg cursor-pointer" 
              width={"100%"} 
              height={'100%'} 
              layout="responsive"/>
            </div>
          </div>
        </section>
      </main>
    
    </div>
  )
}
